#!/usr/bin/ruby

colours = [
	"\u001b[31m", # Red
	"\u001b[32m", # Green
	"\u001b[33m", # Yellow
	"\u001b[34m", # Blue
	"\u001b[35m", # Magenta
	"\u001b[36m", # Cyan
]

reset = "\u001b[0m"

Signal.trap("INT") {
	puts reset
	exit
}

Signal.trap("TERM") {
	puts reset
	exit
}

STDIN.each_line do |line|
	nesting = 0
	inside = false
	just_inside = false
	increment = 0
	in_string = false

	line.each_char do |char|
		case char
		when '<'
			print reset
			just_inside = true
			inside = true
		when '/'
			unless in_string
				increment = 1
				if just_inside
					print colours[nesting % colours.size]
				end
			end
			just_inside = false
		when '>'
			print reset
			just_inside = false
			inside = false
			nesting -= increment
			increment = 0
		when '"', "'"
			in_string = !in_string
		else
			if just_inside
				nesting += 1
				print colours[nesting % colours.size]
			end
			just_inside = false
		end
		print char
	end
	print reset
end

puts reset
